name: Auto Merge PRs

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    if: github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge if CI passed
        uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
